version: '2'
services:
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - '27017:27017'